// PHASE 2 EVENTS DATA

const P2_EVENTS = [
    { id:'stray_dog', day:[1,8], type:'bond', once:true, companionId:'dog',
      title:'门外的流浪狗', avatar:'🐕',
      desc:'一只伤痕累累的德牧在门外刨土，嘴里叼着包裹。看到监控亮了，冲你摇了摇尾巴。',
      left:{ label:'开门 + 喂食', cost:{food:5},
        text:'它扑进来舔你的手。包裹里是一件防弹衣。', defBonus:10 },
      right:{ label:'关门', euph:5, exposure:2,
        text:'狗蹲了一夜。天亮后消失了。' } },
    { id:'neighbor', day:[3,10], type:'resource', once:true,
      title:'楼上王大爷', avatar:'👴',
      desc:'83岁的王大爷颤巍巍敲门："孩子，能匀两瓶水吗……大爷给你磕头了。"',
      left:{ label:'给水+药', cost:{water:3,med:1},
        add_flags:['neighbor_helped'],
        text:'他留下珍藏40年的收音机。（每日+5爽度）', euphPerDay:5 },
      right:{ label:'装没人', euph:15, exposure:3,
        add_flags:['neighbor_rejected'],
        text:'缓慢的脚步声远去。群聊有人说王大爷倒在楼道了。' } },
    { id:'recruit_owl', day:[5,15], type:'bond', once:true, companionId:'owl',
      title:'坠毁的直升机', avatar:'💎',
      desc:'监控画面：三公里外有黑烟升起。一个穿着高定大衣的女人踉踉跄跄走来，浑身是灰，但气场依然压人。\n\n她敲了敲门，不是求救的语气——是命令的语气："我知道你这里有发电机。我需要接入卫星链路。开门，我让你这个破避难所升三个档次。"',
      left:{ label:'开门（她说的卫星是真的？）', cost:{water:2},
        text:'她一进门就接管了你的电脑，十分钟后——你的监控范围从50米扩展到了3公里。"这只是开胃菜。"她说。暴露度大幅下降。', exposureReduce:15 },
      right:{ label:'谁知道她是不是骗子', euph:5, exposure:3,
        text:'她看了你的摄像头一眼，转身离开了。消失在风雪中。\n\n你在门口发现了她丢下的一个小包裹——里面有几瓶净水和一张名片。名片背面写着："你会后悔的。"' } },
    { id:'ex_colleague', day:[6,18], type:'drama', once:true,
      title:'前同事的求生语音', avatar:'👩‍💼',
      npcCode:3175,
      npcTag:'黑市黄牛',
      npcHook:'道德抉择：救人，可能等于暴露你的家。',
      desc:'避难所通讯终端突然亮起，收到一段带有【黑市黄牛】高危红色标识的加密语音。\n\n前公司那个曾经常抢你功劳、对你颐指气使的女同事，此刻正用濒死般的喘息哭着求救："求求你……我高烧40度，只要一口水、一片药……我给你跪下了。"\n\n你很快意识到：她为了发出这条语音，已经把你避难所的大致频段抵押给了黑市黄牛。只要你通过死信箱送出物资，对方就能反向追踪你的精确坐标。',
      left:{ label:'给水和药（-2水 -1药）', cost:{water:2,med:1},
        add_flags:['colleague_helped'],
        text:'你最终还是把水和药送了出去。\n\n公频里传来她怯懦却真诚的哽咽道谢："我……我记住这条命了。"\n\n你知道自己正在承担坐标暴露的代价，但也守住了最后的人性底线。',
        reward:{euph:18} },
      right:{ label:'"多喝热水 :)"（拒绝）', euph:-18, exposure:0,
        add_flags:['colleague_refused'],
        text:'你只回了四个字："多喝热水 :)"\n\n两天后，区域广播的尸体清理名单里出现了一段和她高度吻合的特征描述。\n\n避难所很安全，你却盯着那条消息看了很久。' } },

    { id:'colleague_hackback', day:[12,34], type:'drama', once:true, base_weight:135,
      conditions:{ required_flags:['colleague_helped'] },
      title:'黑市反向追踪', avatar:'🛰️',
      npcTag:'羁绊解锁',
      npcHook:'善良不是白给，它可能在最危险时刻回头救你。',
      desc:'几天后，雷达出现异常：黑市掠夺者侦察无人机开始在避难所外围低空盘旋，武装人员正在集结。\n\n就在你准备迎接爆破的时候，敌方雷达和火力引导系统突然大面积掉线。\n\n第二条加密语音切进来，是她压低的声音："我在他们的后端系统里，给你开了30秒盲区窗口。火力盲区图已经发过去了……以前在公司是我对不起你，这次换我还你的命。"\n\n你握紧终端，看着那张实时更新的盲区图，第一次在末日里感到‘被托付’而不是‘被背叛’。',
      left:{ label:'按盲区图反击（高收益）', cost:{},
        add_flags:['colleague_ally'],
        text:'你按她给的盲区坐标布置火力，掠夺者队伍在错误指引下自乱阵脚。\n\n反击结束后，你缴获了一批黑市补给。频道另一端只留下一句气若游丝的笑："这次，算我们扯平。"',
        reward:{food:6,water:4,med:2,defense:10}, exposureReduce:12 },
      right:{ label:'锁门死守，不冒险', euph:10, exposure:5,
        text:'你没有贸然出击，选择加固避难所硬扛冲击。敌方在系统混乱中短暂失序后撤离。\n\n你保住了安全，但也错过了反杀窗口。那条语音再没亮起。' } },
    { id:'recruit_hunter', day:[8,20], type:'bond', once:true, companionId:'hunter',
      title:'满身弹孔的杀手', avatar:'🗡️',
      desc:'监控画面：黑色作战服的短发女人跌跌撞撞走来，腹部在流血，手里攥着军刀。她身后——三个持枪暴徒正在逼近。\n\n她没有敲门。她靠在门上，用刀在金属板上刻了一行字："债主派我来杀你。他们先杀了我。"',
      left:{ label:'开门 + 火力掩护', cost:{med:5,food:3,water:3},
        text:'你拖她进来的瞬间，她反手一刀切断了追踪器。"……两清了。但那三个人我得出去解决。" 三分钟后她回来了，浑身是血，手里多了一箱军粮。', exposureReduce:10 },
      right:{ label:'她说过要杀你', euph:5, exposure:5,
        text:'三声枪响。然后是沉默。雪地上只剩军刀和一滩血。' } },
    { id:'recruit_chef', day:[12,25], type:'bond', once:true, companionId:'chef',
      title:'背着锅的女人', avatar:'👩‍🍳',
      desc:'衣着讲究但疲惫的女人站在门口，背上居然背着铸铁锅。"我是厨师。给我食材，我让你吃到米其林。"',
      left:{ label:'收留', cost:{food:8},
        text:'她用压缩饼干做出让人流泪的晚餐。食材消耗降低了。' },
      right:{ label:'不需要厨师', euph:10, exposure:3,
        text:'她抱着锅消失在风雪中。你打开自热火锅，突然索然无味。' } },
    { id:'ex_bf', day:[10,28], type:'drama', once:true, excludeIfMeta:'expack',
      title:'软饭男前任来电', avatar:'📵',
      npcCode:4671,
      npcTag:'软饭男',
      npcHook:'嘴上求和，脚下带刀。',
      desc:'你正瘫在恒温沙发上撸狗，通讯器突然刺耳地响起。\n\n屏幕跳出一个让你生理不适的头像——那个白吃白喝、极要面子、末日前还偷开你跑车私奔的软饭男前任。\n\n"宝……宝贝，我快冻死了……我们和好吧？我有车，我什么都给你……"\n\n你看了眼室外温度。燃油早就冻成渣了，他那辆车现在连废铁都算不上。',
      left:{ label:'让对方进来', cost:{},
        special:'exBfBreach',
        text:'气闸门缓缓打开，风雪先一步灌进来。\n\n进来的却不止他一个。' },
      right:{ label:'挂断+拉黑', euph:45, exposure:0,
        text:'你手指一划，世界清净。\n\n你顺手把门外监控投到4K墙屏。刚才还深情款款的前任立刻破口大骂，下一秒就被几只饿疯的变异野狗追得抱头鼠窜，连空背包都丢在雪地里。\n\n避难所里笑成一片，脚边的金毛都跟着叫了两声。\n\n你抿了口冰镇可乐：在末日，看背叛你的人被社会毒打，确实很下饭。' } },
    { id:'mystery_box', day:[10,25], type:'random', once:true,
      title:'神秘包裹', avatar:'📦',
      desc:'门口出现无标记金属箱。纸条："给还活着的人。——一个已经走了的人"',
      left:{ label:'打开', cost:{},
        randomOutcomes:[
          { chance:0.5, text:'十几份军用口粮和净水片！', reward:{food:8,water:6} },
          { chance:0.3, text:'一套破损的防弹装甲！', reward:{defense:8} },
          { chance:0.2, text:'只有遗书和全家福。你沉默了很久。', reward:{euph:15} }
        ] },
      right:{ label:'可能是陷阱', euph:5, exposure:0,
        text:'你盯了它三天。第三天有人搬走了。' } },
    { id:'recruit_seed', day:[15,30], type:'bond', once:true, companionId:'seed',
      title:'染血白大褂的女医生', avatar:'💉',
      desc:'凌晨两点。监控里出现一个穿着白大褂的女人，肩上扛着一个巨大的急救箱，膝盖在流血但步伐很稳。\n\n她对着摄像头举起医师执照："我是外科医生。我能治任何伤。你收留我，我保你这里没有人会死。"\n\n她的声音很温柔，但眼神异常冷静。',
      left:{ label:'开门（医生太稀缺了）', cost:{food:2,water:3},
        text:'她一进门就给自己的膝盖做了缝合，没打麻药，一边缝一边跟你聊天。\n\n然后她检查了你的物资清单，微笑着说："你囤的东西不错。以后你的健康，我全包了。"',
        euphPerDay:3 },
      right:{ label:'不需要医生', euph:-5, exposure:0,
        text:'她在门外站了一会儿，然后把急救箱里的一盒止痛药放在门口。纸条："你迟早需要我的。"\n\n三天后你被冻伤了，发现那盒药救了你的命。' } },
    { id:'gang_threat', day:[12,58], type:'threat', once:false, cooldown:8,
      title:'暴民最后通牒', avatar:'💀',
      desc:'对讲机沙哑的声音："我们知道你在里面。交出一半物资。不然——你知道后果。"',
      left:{ label:'交物资求和', cost:{food:10,water:8},
        text:'你推出一箱物资。脚步声远去。暂时安全。', exposureReduce:10 },
      right:{ label:'一个字：滚', euph:35, exposure:15,
        text:'"你有种。"那头沉默了。"我们会回来的。"' } },
    // SSR 羁绊深化事件
    { id:'owl_bond_up', day:[20,35], type:'bond_event', once:true, requiresCompanion:'owl',
      title:'卫星链路全开', avatar:'💎',
      desc:'宁鸮把你叫到电脑前。屏幕上是一张实时卫星地图——整个城市的废墟一览无余。\n\n"我家族的卫星网络全部接通了。"她推了推眼镜。"现在我可以调动无人机做空投，但需要你的发电机全功率运转48小时。期间避难所会停暖。"\n\n"值不值得，你说了算。"',
      left:{ label:'全功率（停暖两天）', cost:{food:5},
        text:'冻了两天。但——卫星网络全开。无人机空投了一整箱顶级补给。宁鸮靠在你肩上看着满屏绿点："以后别人还在翻垃圾桶，我们从天上收快递。"暴露度大幅下降。', exposureReduce:25, reward:{food:8,water:5,med:3} },
      right:{ label:'别折腾了', euph:10, exposure:0,
        text:'"行吧。有钱人的提案被穷鬼否决了。"她耸耸肩，但没生气。"你的避难所，你做主。"' } },
    { id:'hunter_bond_up', day:[25,40], type:'bond_event', once:true, requiresCompanion:'hunter',
      title:'刀背上的名字', avatar:'🗡️',
      desc:'楚狄高烧不退。你给她换冰毛巾时发现她攥着军刀不放——刀背上刻着一个被划掉的名字，隐约能看出是……你的名字。\n\n她烧迷糊了，抓住你的手："……目标已锁定……取消任务……取消……"\n\n她在说梦话。关于那个暗杀任务。关于她为什么在你开门的那一刻没有动手。',
      left:{ label:'握住她的手（留下来）', cost:{med:2,water:1},
        text:'你握了一整夜。天亮时她退烧了，看见你红肿的眼睛。沉默很久，然后把军刀递给你："帮我把那个名字彻底磨掉。"\n\n从今以后，她的刀只为你而拔。', defBonus:15 },
      right:{ label:'放下药就走', euph:15, exposure:0,
        text:'你放下她的手。半夜听到角落传来很轻的、像是在忍耐什么的呼吸声。' } },
    { id:'seed_bond_up', day:[30,45], type:'bond_event', once:true, requiresCompanion:'seed',
      title:'她的独占欲', avatar:'💉',
      desc:'一个受伤的女幸存者敲门求救。你准备开门，黎冥拦住了你。\n\n"她身上有未知病原体。"黎冥微笑着说。\n\n你检查了监控。那个女人看起来完全健康。\n\n黎冥注意到你的怀疑。她的笑容没变，但声音轻了一度："你不信我？"\n\n沉默。\n\n"……我只是不想让任何人伤害你。这里的药不够分给外人。你明白的，对吧？"',
      left:{ label:'"我信你。不开门。"', cost:{},
        text:'黎冥的眼睛亮了。她从背后抱住你："我就知道你最懂我。"\n\n那个女人最终离开了。你不确定自己做了对的选择。但黎冥今晚做的晚餐，是你吃过最好吃的一顿。\n\n（HP回满，每日爽度+8）', euphPerDay:8, special:'seedBondMax' },
      right:{ label:'"让我自己判断。开门检查。"', euph:0, exposure:3,
        text:'你开了门。那个女人确实没有病。你给了她一些物资。\n\n黎冥全程站在角落，微笑着，一言不发。但接下来三天她做的饭都没什么味道。\n\n第四天一切恢复正常。她端着一碗热汤走过来："我想通了。你心善是好事。但下次——让我先检查，好吗？"' } },
    { id:'radio_signal', day:[20,40], type:'resource', once:true,
      title:'未知无线电', avatar:'📡',
      desc:'收音机收到加密信号："北区物资站未被发现。仅限1人。48小时有效。"',
      left:{ label:'派同伴前往', cost:{}, requireCompanion:true,
        text:'同伴带回补给！但她说那里有人活动的痕迹……', reward:{food:8,water:5,med:1} },
      right:{ label:'太可疑', euph:5, exposure:0,
        text:'没有上当。或者，错过了救命的补给。谁知道呢。' } },
    { id:'child_cry', day:[25,45], type:'emotional', once:true,
      title:'凌晨三点的哭声', avatar:'👧',
      desc:'凌晨3点，监控里出现裹着毛毯的小女孩。大概五六岁，一个人站在暴风雪里哭。没有大人。',
      left:{ label:'开门', cost:{food:3,water:2,med:1},
        text:'她不说话，只抱着你的腿。同伴们轮流照顾她。避难所有了真正的笑声。', euphPerDay:8 },
      right:{ label:'……', euph:-10, exposure:0,
        text:'你关掉监控。整夜没睡。第二天画面里已经没有人了。' } },
    { id:'scavenger', day:[5,55], type:'resource', once:false, cooldown:6,
      title:'独行拾荒者', avatar:'🧥',
      desc:'沉默的蒙面人出现在监控，举起纸板："以物易物。食物换药品。公平交易。"',
      left:{ label:'交易', cost:{food:5},
        text:'公平交易完成。你得到了急需的医疗物资。', reward:{med:3} },
      right:{ label:'不交易', euph:3, exposure:1,
        text:'蒙面人站了一会儿，默默离开。' } },
    { id:'weather', day:[8,55], type:'random', once:false, cooldown:7,
      title:'极端天气警报', avatar:'🌨️',
      desc:'气温骤降至-65°C。供暖系统在极限运转。今夜将是最难熬的一晚。',
      left:{ label:'全力供暖', cost:{food:3},
        text:'所有人挤在一起度过了这一夜。消耗额外食物，但都活下来了。' },
      right:{ label:'节约物资硬扛', euph:0, exposure:0,
        text:'你决定硬扛。有人冻伤了，消耗医疗物资。', penalty:{med:2} } },
    { id:'broadcast', day:[50,58], type:'resource', once:true,
      title:'最后的广播', avatar:'📻',
      desc:'收音机传来微弱声音："这里是……南方安全区……坐标……幸存者……请坚持……"信号断了。',
      left:{ label:'记录坐标', cost:{},
        text:'你把坐标刻在墙上。也许这不是终点，而是新的起点。', reward:{euph:50} },
      right:{ label:'可能是假的', euph:10, exposure:0,
        text:'末日还能相信什么？守好脚下的一亩三分地。' } },

    // 一、"高空吃瓜"类：极致情绪释放与降维打击
    { id:'ex_rescue', day:[8,30], type:'drama', once:true,
      title:'前任的求救信号', avatar:'📡',
      desc:'监控网络拦截到一条公频求救信号——你那个在末日前卷走你最后一笔存款跑路的前任，正被几个暴徒堵在废弃超市里。\n\n监控画面清晰到你能看见对方脸上的绝望。',
      left:{ label:'远程火力支援', cost:{food:5,med:2},
        text:'你消耗了宝贵的资源进行远程支援。前任得救了——然后系统提示："对方已屏蔽你的通讯并带走了战利品。"\n\n你盯着屏幕，感受到了比末日更深的寒意。' },
      right:{ label:'开一瓶拉菲看戏 🍿', euph:60, exposure:0,
        text:'你打开了82年的拉菲，调暗灯光，把超市监控投屏到4K投影仪上。\n\n"真人秀"持续了四十分钟。你给自己续了第二杯。身边的同伴们面面相觑。\n\n末日最爽的事：看前任被社会毒打。' } },

    { id:'moral_kidnap', day:[10,35], type:'drama', once:true,
      title:'业主群的道德审判', avatar:'📢',
      desc:'业主群炸了。居委会王阿姨正在痛骂："某栋某户（你的坐标）自私自利！囤了那么多物资不分给老人小孩！"\n\n九十九条语音消息轮番轰炸。有人在群里发了你避难所的门牌号。',
      left:{ label:'扔10包大米求清静', cost:{food:10},
        trapChance:0.8, trapText:'暴徒根据大米包装袋上的指纹和供应商信息追踪到了你！', trapExposure:30,
        safeText:'群里暂时安静了。但你知道这只是开始。', safeEuph:5 },
      right:{ label:'发自拍：泡浴缸+吃和牛🥩🛁', euph:80, exposure:10,
        text:'你拍了一张在恒温浴缸里享用A5和牛的自拍，发到群里。然后拉闸切断整栋楼的备用电源。\n\n群里最后一条消息是王阿姨的语音："你……你还是人吗……"\n\n你关掉手机，又切了一块牛排。' } },

    { id:'livestream_drama', day:[12,45], type:'drama', once:false, cooldown:10,
      title:'废土导师直播间', avatar:'📺',
      npcCode:1800,
      npcTag:'情绪炸弹',
      npcHook:'开口先讲格局，结尾必借物资。',
      desc:'你截获到一个局域网直播。\n\n镜头里，一个自称"末日前跨国公司VP"的男人，坐在拼出来的总裁布景前疯狂输出：\n\n"外面有丧尸和酸雨都只是借口。你们挨饿，是因为格局不够。交一箱物资做天使轮，我带你们进‘废土独角兽’项目。"\n\n公共频道里，真有人哭着问："导师，我只剩半包发霉面饼，算不算投资？"',
      left:{ label:'匿名打赏一箱物资（-8 食物）', cost:{food:8},
        add_flags:['mentor_seeded','mentor_scammed'],
        text:'你投了8单位食物，想看看这套课能离谱到什么程度。\n\n回传文件几十个G，内容全是空话鸡汤：\n《丧尸危机中的心力增长》\n《情绪黑洞管理》\n\n结尾一句最精华："没收到物资，说明你执行力不够。"\n\n你关掉播放器，沉默了很久。', reward:{euph:-30} },
      right:{ label:'开投影仪看直播吃瓜（免费）', euph:45, exposure:0,
        add_flags:['mentor_seeded','mentor_exposed'],
        text:'你泡了杯速溶咖啡，切到外圈监控吃瓜。\n\n三天后你确认：所谓"投资坐标"，其实是掠夺者据点。\n\n导师不是什么VP，只是营地首席大忽悠。\n\n你记下一句：在废土，相信"努力就能活"的人，通常死得最快。' } },

    { id:'mentor_masterclass', day:[20,45], type:'drama', once:true, base_weight:145,
      conditions:{ required_flags:['mentor_seeded'] },
      title:'导师的闭门私董会', avatar:'🧠',
      npcCode:1800,
      npcTag:'情绪炸弹',
      npcHook:'识破骗局只是及格，让骗子付成本才算反击。',
      desc:'导师把直播升级成"闭门私董会"。\n\n白板上只写一句：\n"资源焦虑=认知税。"\n\n入场门槛也很直接：交6单位食物，买一份"强者方法论"。',
      left:{ label:'交押金进群（-6 食物）', cost:{food:6},
        add_flags:['mentor_scammed_deep'],
        text:'你交了6单位食物。\n\n回来的课程就三句：服从、加投、别质疑。\n\n最后一页还补刀：\n"你觉得没用，说明你层级不够。"\n\n你第一次理解了什么叫高级PUA。', reward:{euph:-20} },
      right:{ label:'反向设局，放出假交割路线', euph:45, exposure:8,
        add_flags:['mentor_countered'],
        text:'你伪装成大额投资人，喂了一条假交割路线。\n\n他们整队离开据点后，你把录音公开，再把路线丢给敌对掠夺者。\n\n三小时后，导师频道只剩破音怒吼：\n"你们这是恶意做空我的信任资产！"\n\n你记下：识破骗局只是及格，让骗子付成本才叫自救。',
        reward:{food:4,water:3}, defBonus:8 } },

    { id:'mentor_collapse', day:[30,55], type:'drama', once:true, base_weight:120,
      conditions:{ required_flags:['mentor_countered'] },
      title:'导师人设崩盘', avatar:'📉',
      npcCode:1800,
      npcTag:'反杀时刻',
      npcHook:'把镰刀折断的人，才有资格定义秩序。',
      desc:'凌晨，你收到一段残缺回放。\n\n导师缩在半塌车库里，满头是汗地辩解：\n"那不是骗局，是资源优化配置。"\n\n弹幕没人再叫他老师，只剩坐标截图和被骗清单。\n\n几分钟后通报刷屏：信息组补给链被连根端掉，首席话术师失联。',
      left:{ label:'公开反诈手册（+区域声望）', cost:{},
        text:'你把证据整理成《废土反诈十条》丢上公频。\n\n避难所开始共享黑名单，骗子话术命中率断崖下跌。\n\n你记下：在末日，知识就是防爆门。',
        reward:{euph:25,defense:8}, exposureReduce:8 },
      right:{ label:'静默观望，继续收集样本', euph:35, exposure:0,
        text:'你不发声，只把证据加密归档，继续监听残余频道。\n\n三天后你提前绕开同类陷阱，还捞回一批弃置补给。\n\n日志里只有一句：\n"真正的优势，不是会演讲，是活得比骗子久。"',
        reward:{food:5,water:4,med:1} } },

    { id:'revenge_delivery', day:[18,42], type:'drama', once:true,
      title:'快递员的末日复仇', avatar:'📦',
      npcTag:'末日骗局',
      npcHook:'话术离谱，但总能戳中人性弱点。',
      desc:'监控里，一个穿破烂快递服的男人举着巨型包裹，哭着大喊：\n\n"三年前你给我差评，害我被公司开除，后来连房租都交不起。今天我就把这个‘好评’包裹送给你。开门！不然我就死在你门外！"\n\n他演得很真，连手都在抖。\n\n问题是：你根本没给过快递员差评。\n\n这更像一场为"心软的人"准备的敲门测试。',
      left:{ label:'开门签收', cost:{},
        special:'courierAmbush',
        text:'门锁弹开的那一刻，他的哭腔瞬间消失。\n\n死角里冲出同伙，走廊枪声炸开。你被迫退回第二道门后，才勉强把局面封住。\n\n这单"快递"，果然带着刀。' },
      right:{ label:'先回一句再说', euph:25, exposure:0,
        add_flags:['courier_exposed'],
        text:'你开扩音器只说一句：\n\n"我没给过你差评。"\n\n门外安静了两秒。对方擦掉眼泪，抱起包裹，向暗处打了个手势就撤了。\n\n你在日志里写下：不是每次敲门都该开门。' } },

    { id:'courier_anti_fraud', day:[20,55], type:'drama', once:true, base_weight:130,
      conditions:{ required_flags:['courier_exposed'] },
      title:'全区反诈播报', avatar:'📡',
      npcCode:9096,
      npcTag:'反诈节点',
      npcHook:'你的一次识破，可能成为很多人的活路。',
      desc:'你把"假快递差评复仇"话术录音、伏击位示意图和识别要点整理成一份简报，投进公共频道。\n\n起初没人信，直到当晚同样台词在另一栋楼被完整复读。那次，对方等来的不是心软住户，而是一扇永远不开的门和一串可核验证据。\n\n三天后，这种骗局在本区明显失效。频道里有人发来一句很短的消息："谢谢你。我们差点就开门了。"',
      left:{ label:'公开署名发布（高风险）', euph:35, exposure:10,
        add_flags:['anti_fraud_named'],
        text:'你用真实频道签名发布手册，瞬间成为多个避难所口中的"反诈节点"。\n\n合作请求涌入的同时，你也注意到黑市频道开始反复出现你的代号，像是在做某种标记。\n\n你知道：这一步救了很多人，也把自己推到了骗子的瞄准镜里。',
        defBonus:6 },
      right:{ label:'匿名投放不留痕迹', euph:25, exposure:0,
        add_flags:['anti_fraud_anon'],
        text:'你清除了所有元数据，只保留可核验事实和防骗流程。\n\n没人知道你是谁，但骗子的话术命中率开始断崖下跌。公共频道里，多了越来越多互相验证坐标的幸存者。',
        reward:{med:2}, exposureReduce:6 } },

    { id:'anti_fraud_retaliation', day:[28,58], type:'threat', once:true, base_weight:125,
      conditions:{ required_flags:['anti_fraud_named'] },
      title:'反诈名单上的名字', avatar:'🎯',
      npcCode:9096,
      npcTag:'报复来袭',
      npcHook:'救人会被记住，打脸也会被记仇。',
      desc:'凌晨四点，公共频道突然刷出一条匿名悬赏：\n\n"提供反诈节点坐标者，赏标准口粮两箱。"\n\n不到半小时，你楼道外的脚步声开始增多。红外画面里，三伙不同来路的人正在你所在楼层徘徊、互相试探。\n\n你很清楚：这不是一次单纯袭击，而是一次公开"杀鸡儆猴"。骗子想用你的下场，堵住其他人的嘴。',
      left:{ label:'先交物资买时间（稳损）', cost:{food:10,water:6},
        text:'你把一批低级物资推到外门缓冲区，制造"已有人先拿到好处"的假象。\n\n几伙人果然互相猜忌，当场争执起来，最终各自撤离。\n\n你保住了今晚，但仓库明显瘦了一圈。',
        exposureReduce:8 },
      right:{ label:'反向广播假坐标（高风险反击）', euph:40, exposure:12,
        add_flags:['anti_fraud_survived'],
        text:'你打开公网广播，故意放出一组"高价值物资转运点"假坐标，并附上伪造的频道签名。\n\n徘徊在楼道里的几伙人很快被更大的利益吸走，连夜转场。\n\n次日你从监控里看到：那片区域爆发了激烈火并。你关掉画面，把这条记录命名为《骗局生态的自噬》。',
        defBonus:10, reward:{food:4,water:3} } },

    { id:'influencer_beg', day:[10,28], type:'drama', once:true,
      title:'破防的爹味亲戚', avatar:'🧨',
      npcTag:'神棍邻居',
      npcHook:'血缘不是通行证，规矩也不是勒索券。',
      desc:'监控里，是那个总在背后造谣打压你的大伯。\n\n他盯着你坚固的避难所，嫉妒到五官扭曲，砸不开门后开始无能狂怒：\n\n"开门！你守得住这么多东西吗？赶紧把密码交出来让我统一管理！二叔三姑都在挨饿，你懂不懂规矩？懂不懂孝顺长辈？别给脸不要脸！"',
      left:{ label:'中等疼痛电击', euph:40, exposure:0,
        text:'你看着屏幕，淡漠地把门表微电流调到"中等疼痛"。\n\n合金门闪过几道细蓝电弧。伴随一声惨叫，他像被蝎子蛰到一样猛地弹开，焦黑的手在雪地里乱甩，威严瞬间蒸发。\n\n你随手切断音频，世界安静了。' },
      right:{ label:'扩音器谈条件', euph:40, exposure:0,
        text:'你对着扩音器冷冷说："可以给你一罐狗粮。跪在摄像头前，磕头。"\n\n他僵住了。饥饿和尊严在脸上打架。最终还是双膝落地。\n\n你把一罐受潮狗粮从投递口扔出去，又在他伸手前启动自动除尘系统，把狗粮扫进废料池。\n\n你喝了口温水，转身继续保养十字弩。' } },

    // 二、硬核科幻/AI类：算力博弈与底层设施
    { id:'ai_overclock', day:[18,35], type:'tech', once:true,
      title:'AI中枢的算力越权请求', avatar:'🤖',
      desc:'避难所主控AI发出红色警报——\n\n"检测到外部军方遗留HPC集群节点。请求授权：切断全部生活娱乐设施电源，执行48小时超频运算以破解该节点。\n\n预期收益：接入军方战术雷达网络。\n代价：停电期间恒温冰柜停机，部分高级食材将损坏。娱乐设施停转，爽度产出归零。"',
      left:{ label:'授权超频（停电2天）', cost:{food:8},
        text:'漫长的48小时。没有灯光、没有暖气、没有娱乐。你们靠体温和蜡烛熬过了两个黑夜。\n\n但——军方雷达成功接入。战术预警系统永久上线。\n\n从今以后，所有右滑事件带来的暴露度惩罚减半。',
        special:'tacticalWarning' },
      right:{ label:'拒绝授权', euph:15, exposure:0,
        text:'"授权被拒。系统将在允许范围内持续尝试。"\n\nAI核心因逻辑冲突产生轻微冗余——下一次遭遇袭击时，防爆门响应将延迟3秒。\n\n（防御力临时下降3天）',
        special:'defDebuff' } },

    { id:'power_grid_hack', day:[22,40], type:'tech', once:true,
      title:'电网幽灵', avatar:'⚡',
      desc:'凌晨，避难所的灯光开始不规律闪烁。AI报告：\n\n"检测到未知信号正在尝试接管本地电力分配系统。信号源：3.7公里外的废弃变电站。\n\n分析：该信号可能来自其他幸存者的自动化系统——或者是一个陷阱。\n可选方案：主动出击控制变电站 / 切断外网隔离防御。"',
      left:{ label:'主动出击（需同伴）', cost:{food:5,med:2}, requireCompanion:true,
        text:'同伴带队突入变电站。发现是一个废弃的自动化防御系统在无目的地搜索可用电网。\n\n你们成功接管了它——避难所供电效率提升50%。恒温冰柜终于能全功率运转了。',
        reward:{euph:20}, euphPerDay:5 },
      right:{ label:'切断外网隔离', euph:10, exposure:0,
        text:'你选择了最安全的方案。灯光恢复了稳定。\n\n但三天后，你在监控里看到变电站方向亮起了灯——有人比你更勇敢，或者更愚蠢。' } },

    { id:'drone_swarm', day:[28,48], type:'tech', once:true,
      title:'天空中的蜂群', avatar:'🛸',
      desc:'清晨，监控捕捉到天空中出现一大群无人机——至少二十架，以完美的编队飞行。\n\n它们不属于任何已知势力。其中一架脱离编队，悬停在你的避难所上方，开始扫描。\n\n你有大约三十秒做出决定。',
      left:{ label:'电磁脉冲干扰（消耗发电机功率）', cost:{food:3},
        text:'你启动了发电机的电磁干扰模式。扫描无人机失去信号坠落，其余编队偏转航向离开。\n\n你拆解了坠落的无人机——里面有一块军用级别的通讯芯片。\n\n（暴露度-15，防御+8）',
        exposureReduce:15, defBonus:8 },
      right:{ label:'关闭一切信号装死', euph:0, exposure:8,
        text:'你切断了所有电子设备。避难所陷入死一般的沉默。无人机悬停了整整四分钟——然后离开了。\n\n但你不确定它是否已经记录了你的位置。' } },

    { id:'quantum_comm', day:[35,52], type:'tech', once:true,
      title:'量子加密频道', avatar:'🔐',
      desc:'AI系统突然弹出一条从未见过的通讯协议——量子加密。解密后是一条简短的消息：\n\n"我们是极光计划幸存者。坐标已锁定。7天后接应。请保持避难所运转。\n——编号：AURORA-07"\n\n消息的加密等级暗示这可能来自政府级别的组织。或者是最精密的陷阱。',
      left:{ label:'回复确认+发送坐标', cost:{},
        text:'你发送了回复。三天后，一个空投物资箱落在避难所500米外。里面有最顶级的医疗设备和一张手写纸条："坚持住。我们来了。"\n\n你不知道他们是谁。但这是末日以来，第一次觉得未来不只有黑暗。',
        reward:{food:10,water:8,med:3,euph:15} },
      right:{ label:'忽略（太像陷阱了）', euph:5, exposure:0,
        text:'你没有回复。频道在24小时后自动关闭。\n\n你永远不知道那是不是真的。但在末日，怀疑比信任更安全。\n\n……大概吧。' } },

    // 三、悬疑惊悚类：打破绝对安全的错觉
    { id:'vent_echo', day:[12,30], type:'horror', once:true,
      title:'通风管里的回声', avatar:'👁️',
      desc:'连续三个深夜，凌晨两点整，避难所最深处的通风管道里都会传来指甲抓挠金属的声音。\n\n第一晚你以为是风。第二晚你确认不是。第三晚——你听到了呢喃声。微弱的、像是在念名字的呢喃声。\n\n你的名字。',
      left:{ label:'消耗资源彻底排查', cost:{food:3,med:1},
        text:'你和同伴们花了六个小时拆开管道进行全盘扫描。\n\n最终发现——是一只变异的巨型老鼠。它的声带因为辐射产生了类人的共振频率。\n\n楚狄一刀结果了它。陈婉说："……这个太大了，不考虑加餐。"\n\n你松了一口气。但今晚还是睡不着。' },
      right:{ label:'封死管口不管它', euph:0, exposure:0,
        text:'你用钢板焊死了通风口。但声音变成了从墙壁里传来。越来越清晰。\n\n同伴们开始失眠。三天后，每个人的眼底都出现了青黑色。\n\n（全体同伴被动技能失效3天）',
        special:'companionDebuffAll' } },

    { id:'mirror_self', day:[20,42], type:'horror', once:true,
      title:'监控里的自己', avatar:'🪞',
      desc:'凌晨，你习惯性地检查监控。\n\n外部摄像头画面正常——空无一人的走廊。但内部摄像头03号捕捉到了诡异的画面：\n\n画面里，你正坐在餐桌前吃东西。但你现在明明站在监控室里。\n\n你低头看了看自己。再抬头——画面里的"你"也抬起了头，直直地看向摄像头。\n\n微笑了。',
      left:{ label:'立刻去餐厅确认', cost:{},
        text:'你跑到餐厅。空无一人。桌上有一个还在冒热气的杯子——是你的杯子，你平时用的那个。\n\n你调取了03号摄像头的存储记录。记录显示：过去72小时内，该摄像头从未捕捉到任何异常画面。\n\n宁鸮检查了系统："数据没有被篡改。要么是硬件幻觉，要么……"\n\n她没说完。你们都没再提这件事。', reward:{euph:20} },
      right:{ label:'关闭03号摄像头', euph:-5, exposure:5,
        text:'你关闭了03号摄像头。问题解决了。\n\n大概。\n\n（之后每天凌晨，你都会不自觉地避开那面走廊的镜子。你总觉得镜子里的自己，动作会慢半拍。）' } },

    { id:'dead_radio', day:[28,48], type:'horror', once:true,
      title:'死者的频道', avatar:'📻',
      desc:'收音机突然自己打开了。没有人碰过它。\n\n频道里传来一个女人的声音，语气平静得可怕："第47天。食物耗尽。水还有三瓶。他们都走了。只有我还在。"\n\n停顿。\n\n"如果有人能听到……不要打开地下三层的门。无论听到什么声音。无论多像你认识的人。不要开门。"\n\n信号消失。收音机显示的频率——是一个不存在的频段。',
      left:{ label:'记录并分析信号', cost:{},
        text:'宁鸮分析了信号波形："这不是实时广播。这是……循环播放。至少已经播放了两个月。"\n\n你算了一下日期。录音的时间——比末日爆发还早15天。\n\n那个女人，在末日之前就已经在避难所里了。她在躲什么？',
        reward:{euph:15,defense:5} },
      right:{ label:'关掉收音机拔掉电源', euph:0, exposure:0,
        text:'你关掉了收音机。拔掉了电源线。\n\n半小时后，收音机又响了。同一个频率。同一句话。\n\n你把收音机锁进了储物柜。声音变小了，但没有停。\n\n"不要打开门……不要打开门……"' } },

    { id:'knock_pattern', day:[15,50], type:'horror', once:false, cooldown:12,
      title:'午夜敲门人', avatar:'🚪',
      desc:'凌晨一点。敲门声。\n\n不是暴徒的砸门——是礼貌的、有节奏的敲门声。三下。停顿。三下。停顿。三下。\n\n监控画面：门外空无一人。但敲门声还在继续。\n\n温度传感器显示：门外的温度比周围环境高了整整15度。像是有什么巨大的、温热的东西贴在门上。',
      left:{ label:'用对讲机喊话', cost:{},
        text:'你按下对讲机："谁在外面？"\n\n沉默。然后一个声音回答。用的是你母亲的声音："开门，孩子。妈妈做了你爱吃的红烧肉。"\n\n你的血液冻结了。你母亲三年前就去世了。\n\n敲门声停了。温度恢复正常。监控画面始终空白。你关掉了对讲机，手在发抖。',
        reward:{euph:10} },
      right:{ label:'增加门禁电压（电击）', euph:5, exposure:0,
        text:'你把防爆门的电击系统开到最大。一声闷响。\n\n门外传来什么东西摔倒的声音。然后是拖行的声音。渐渐远去。\n\n天亮后你检查门口——地上有一片焦痕。形状像一只手。\n\n五根指头，但多了一个关节。', penalty:{med:1} } },

    { id:'floor_below', day:[38,55], type:'horror', once:true,
      title:'地下的声音', avatar:'⬇️',
      desc:'你的避难所建在地下一层。但今晚，你清楚地听到了——\n\n从脚下。地下二层。传来了椅子拖动的声音。\n\n这栋楼没有地下二层。建筑图纸上没有。城市规划图上没有。但声音是真实的。\n\n然后你闻到了一股气味。很淡。像是……花香。在零下六十度的末日，不该存在的花香。',
      left:{ label:'凿开地板查看', cost:{food:5,med:2},
        add_flags:['found_floor_below'],
        text:'你们花了一整天凿开了混凝土地板。下面确实有一个空间——一个被封死的旧人防工事。\n\n里面整整齐齐地摆着二十年前的军用物资。保存完好。\n\n角落里有一张办公桌，桌上放着一张泛黄的照片——照片里的人穿着军装，长得和你一模一样。\n\n照片背面写着一行字："第三次了。希望这次能成功。"',
        reward:{food:12,water:10,med:3,defense:5} },
      right:{ label:'用水泥封死裂缝', euph:-5, exposure:0,
        text:'你把裂缝用水泥填死了。声音停了。花香也消失了。\n\n但从那天起，你每晚都会做同一个梦——梦里你站在一个全是花的地下花园，有人在叫你的名字。\n\n醒来时枕头是湿的。你分不清是汗还是泪。' } },

    // 四、羁绊衍生类：SSR同伴专属事件
    { id:'hunter_old_enemy', day:[20,45], type:'companion_exclusive', once:true, requiresCompanion:'hunter',
      title:'杀手的旧主来了', avatar:'🗡️',
      desc:'监控显示：五个全副武装的雇佣兵正在切割避难所的外层装甲。楚狄看到画面的瞬间，拔出了军刀。\n\n"旧主的清洁队。来收尸的。"\n\n她用绷带缠紧了还没痊愈的肋骨。\n\n"开门。让我出去。"',
      left:{ label:'让她出去杀', euph:0, exposure:5,
        text:'门开了。楚狄消失在风雪中。\n\n三分钟。监控画面全是红色。\n\n她回来时浑身是血，左臂脱臼。但五个雇佣兵——一个不剩。她把首领的防弹衣扔在你面前："战利品。"\n\n你用颤抖的手给她接骨。她咬着绷带没吭声。\n\n处理完伤口后，她第一次主动握住了你的手。"……谢谢你让我出去。"',
        special:'hunterBondMax', defBonus:10, cost_after:{med:5} },
      right:{ label:'不许去，用防御硬抗', cost:{food:8,water:5},
        text:'你拦住了她。楚狄眼里闪过愤怒——然后是困惑。她不习惯被人保护。\n\n避难所扛住了攻击。外层装甲有损伤但核心没事。\n\n"他们会回来的。"楚狄说。但她把刀收了回去。', exposureReduce:10 } },

    { id:'owl_airdrop', day:[15,35], type:'companion_exclusive', once:true, requiresCompanion:'owl',
      title:'无人机补给线', avatar:'💎',
      desc:'宁鸮拉你到电脑前。卫星地图上标注了一个红点——五公里外有一座被遗弃的军方补给站。\n\n"我的无人机能飞过去把物资运回来。但需要全功率供电，而且飞行路线会暴露我们的位置。"\n\n她看着你："一箱顶级物资，换暴露度+15。你说了算。"',
      left:{ label:'飞！物资比什么都重要', cost:{food:3},
        text:'无人机升空。宁鸮的手指在键盘上飞舞，引导无人机穿过暴风雪。\n\n二十分钟后，一个巨大的军用补给箱从天而降，砸在避难所门口。里面全是硬通货。\n\n宁鸮推了推眼镜："以前我家无人机是用来送下午茶的。没想到末日了还挺好使。"',
        reward:{food:12,water:8,med:5,defense:5}, special:'owlBondUp' },
      right:{ label:'不值得暴露位置', euph:10, exposure:0,
        text:'"行吧。保守派的选择。"她关掉了卫星地图。"但那箱物资可够吃半个月的。"\n\n你知道她说得对。但暴露度+15在末日意味着什么，你更清楚。' } },

    { id:'triple_bond', day:[38,58], type:'companion_exclusive', once:true,
      title:'圆桌会议', avatar:'💫',
      desc:()=>{
        const s=G.s, hasOwl=s.companions.includes('owl'), hasHunter=s.companions.includes('hunter'), hasSeed=s.companions.includes('seed');
        const allThree=hasOwl&&hasHunter&&hasSeed;
        if(allThree) return '你从睡梦中被吵醒。客厅里，三道身影坐在圆桌旁。\n\n宁鸮在左，双手交叉，眼镜反光。楚狄在右，把玩着军刀。黎冥在对面，安静地泡茶。\n\n宁鸮先开口："最后的日子快到了。我们需要一个作战计划。"\n\n楚狄："杀光所有敲门的就行。"\n\n黎冥微笑着给你推了一杯茶："坐。慢慢聊。"';
        return '你从睡梦中被吵醒。客厅里，同伴们坐在圆桌旁。\n\n'+(hasOwl?'宁鸮双手交叉，眼镜反光。':'')+(hasHunter?'楚狄把玩着军刀。':'')+(hasSeed?'黎冥安静地泡茶。':'')+'\n\n"最后的日子快到了。我们需要一个作战计划。"';
      },
      left:{ label:'坐下来听', cost:{},
        requireMinSSR:2,
        text:()=>{
          const s=G.s, hasOwl=s.companions.includes('owl'), hasHunter=s.companions.includes('hunter'), hasSeed=s.companions.includes('seed');
          const allThree=hasOwl&&hasHunter&&hasSeed;
          if(allThree) return '四个小时的作战会议。宁鸮负责雷达预警和无人机火力支援。楚狄负责近战清扫。黎冥负责医疗保障和……一些她没细说的"生化手段"。\n\n最后三个人同时看向你：\n\n"不管来什么——我们一起扛。"\n\n（组合技解锁：全属性+15%，爽度+20/天）';
          let parts=[];
          if(hasOwl)parts.push('宁鸮负责雷达预警');if(hasHunter)parts.push('楚狄负责近战清扫');if(hasSeed)parts.push('黎冥负责医疗保障');
          return '作战会议持续了四个小时。'+parts.join('，')+'。\n\n最后她们看向你："不管来什么——我们一起扛。"\n\n（组合技解锁：全属性+15%，爽度+20/天）';
        },
        special:'tripleSync' },
      right:{ label:'"你们先聊，我再睡会儿"', euph:30, exposure:0,
        text:'你打了个哈欠转身回房。被世界上最危险的女人们惦记着——末日生存指南没写过这一条。' } },

    // 五、前任来访卡包（局外解锁 pool_id:'expack'）
    // 三张连环事件，通过 flags 系统串联
    { id:'ex_discover', day:[8,22], type:'drama', once:true, pool_id:'expack', base_weight:150,
      title:'迟来的软饭投诚', avatar:'🧥',
      desc:'熟悉的敲门声。\n\n监控画面：一个穿着破烂西装、浑身狼狈的男人正瘫坐在你的避难所门外。他对着通风口，用那种你曾经最厌恶的、带着说教意味的语气大喊——\n\n"我知道你在里面！开门！我是为了你好！外面太危险了，你一个女人家撑不住的……虽然你以前总是太强势，不懂得示弱，但我大男人不记小人过，现在愿意给你一个照顾我的机会！"\n\n他手里死死攥着半块发霉的压缩饼干，另一只手还习惯性地想整理已经塌掉的领带。\n\n你一眼认出他——那个末日前嫌你忙于事业、不够温柔体贴，分手时还嘲讽你"太独立了，根本不需要男人"的前任。',
      left:{ label:'毒舌回击后开门（留着当反面教材）', cost:{food:5,water:3},
        add_flags:['ex_inside'],
        text:'你按下对讲机，冷冷回了一句："既然我这么强势，你这个‘温柔’的废物怎么还没在外面被丧尸保护起来？"\n\n门外沉默了三秒，随后传来带哭腔的道歉。你最终还是打开了第一道门闸。\n\n他一进门就开始赔笑，视线却不停往物资区飘。你记下了这个眼神。' },
      right:{ label:'直接驱逐：外置音响+自动洒水系统', euph:80, exposure:5,
        add_flags:['ex_zapped'],
        text:'你先把外置音响音量调到最大，摇滚鼓点瞬间盖过他的说教；紧接着启动自动洒水系统，把这位"讲究人"从头到脚冲了个透。\n\n他抱着那半块饼干踉跄后退，还想维持体面，结果在台阶上滑了一跤。\n\n你关掉监控声音，端起杯子，心情前所未有地轻松。' } },

    { id:'ex_betrayal', day:[18,35], type:'trap', once:true, pool_id:'expack', base_weight:180,
      conditions:{ required_flags:['ex_inside'] },
      title:'前任的真面目', avatar:'🐍',
      desc:'凌晨三点。你被一阵细微的声响吵醒——你的前任正蹲在物资间里，往包里塞你的医疗物资和纯净水。\n\n看到你的眼神，先是一愣，然后挤出一个笑容："我……我就是整理一下……"\n\n你低头看到手机屏幕：给一个叫"大壮哥"的人发了你的避难所坐标。',
      left:{ label:'没收物资+赶出去', cost:{},
        add_flags:['ex_expelled'],
        text:'你一言不发地拿走了包里的东西，然后打开门。\n\n"滚。"\n\n对方站在风雪中回头看你，嘴唇哆嗦着想说什么。你关上了门。\n\n然后你删掉了手机里所有关于前任的照片。不是因为恨，是因为不值得。',
        reward:{euph:40}, exposureReduce:5 },
      right:{ label:'让对方把坐标发给"大壮哥"（钓鱼执法）', euph:60, exposure:20,
        add_flags:['ex_bait_trap'],
        text:'你微笑着说："发吧。告诉你大壮哥，物资管够。"\n\n对方犹豫了一秒，然后真的发了。\n\n你走到防爆门控制台前，把电网调到最大功率。三小时后，"大壮哥"带着五个人摸过来——踩中了你布置的全部陷阱。\n\n你的前任全程目睹，吓得再也不敢耍花样了。（防御+12）',
        defBonus:12 } },

    { id:'ex_revenge', day:[25,45], type:'threat', once:true, pool_id:'expack', base_weight:160,
      conditions:{ required_flags:['ex_zapped'], exclude_flags:['ex_revenge_done'] },
      title:'前任的复仇', avatar:'💣',
      desc:'监控画面令人倒吸一口凉气——你的前任回来了。但这次不是一个人。\n\n身后站着十几个暴徒，领头的光头大汉一看就不好惹。前任指着你的摄像头，对光头说："就是这个人电了我！里面全是好东西！"\n\n光头咧嘴笑了："放心，哥帮你出气。"\n\n暴徒开始包围避难所。',
      left:{ label:'播放她当初卷钱跑路的录音', cost:{},
        add_flags:['ex_revenge_done'],
        text:'你打开外部广播，播放了一段录音——前任当初跟朋友炫耀"骗了穷鬼20万"的语音。\n\n光头听完，缓缓转向前任。"你骗钱是专业的啊？"\n\n"不不不大壮哥我没有——"\n\n暴徒们互相看了一眼，扛着前任就走了。你在监控前鼓了三下掌。\n\n（暴露度-15，爽度爆表）',
        reward:{euph:100}, exposureReduce:15 },
      right:{ label:'全防御硬抗', euph:30, exposure:10,
        add_flags:['ex_revenge_done'],
        text:'你拉响了警报，加固了防爆门。暴徒砸了两小时，最终骂骂咧咧地走了——你的防御等级让他们无从下手。\n\n你在对讲机里对前任说了最后一句话："咱俩的帐，清了。"\n\n然后关掉了频道。永远地。' } },

    { id:'ex_redemption', day:[30,50], type:'drama', once:true, pool_id:'expack', base_weight:120,
      conditions:{ required_flags:['ex_expelled'], exclude_flags:['ex_dead_outside'] },
      title:'风雪中的道歉信', avatar:'💌',
      desc:'门口的监控拍到一个东西——你的前任留下的包。\n\n打开一看，里面是项链、手表、所有值钱的东西，和一张纸条：\n\n"对不起。这些换不回我欠你的，但至少能换几天的物资。我找到了另一个避难所，不会再来烦你了。如果末日结束了……希望你过得比我好。"\n\n字迹歪歪扭扭。有水渍。你分不清是雪水还是眼泪。',
      left:{ label:'收下物资', cost:{},
        text:'你收下了包。里面的东西确实值不少。\n\n你站在门口看了很久风雪。然后关上了门。\n\n有些人，错过了就是错过了。',
        reward:{food:5,water:3,med:2,euph:20} },
      right:{ label:'把包放回门外', euph:30, exposure:0,
        text:'你把包原封不动放回门外。\n\n监控里，她第二天来取走了包。站在门口犹豫了很久，最终鞠了一躬，消失在风雪中。\n\n你倒了一杯咖啡。苦的。' } },

    // 六、邻居连环事件（基础池 flag 串联演示）
    { id:'neighbor_payback', day:[15,30], type:'resource', once:true, base_weight:130,
      conditions:{ required_flags:['neighbor_helped'] },
      title:'李奶奶的馈赠', avatar:'👵',
      npcTag:'绝望的善意',
      npcHook:'沉甸甸的生命托付，带着对明天最后的期盼。',
      desc:'对讲机里传来一阵撕心裂肺的咳嗽声，随后是李奶奶极度虚弱的喘息："孩子……奶奶实在熬不下去了。这世道太难，我的药也早就断了……就不浪费粮食了。"\n\n她停顿了很久，只剩微弱电流声在空荡走廊回响。仿佛用尽最后力气，她又开口："我都这把老骨头了，死不足惜。可你还有希望。我在你门口放了个布包，里面是我省下来的半瓶干净水，还有一点食物……拿着吧，孩子。替奶奶看看，外面的天还能不能亮。"\n\n通信彻底断了。你切到监控，只看到一个佝偻瘦弱的身影，正步履蹒跚地走向走廊尽头那片吞噬一切的黑暗。门外台阶上，静静躺着一个被塑料袋里三层外三层仔细裹好的旧布包。',
      left:{ label:'含泪收下（免费）', cost:{},
        text:'过了一会，你打开门缝拿走那个破旧的碎花布包。\n\n在这个吃人的末日里，带着她那份一起活下去，或许才是对她最大的尊重。\n\n布包很轻，却重得让你一整晚都睡不着。',
        reward:{food:4,water:3,euph:-20} },
      right:{ label:'递送安眠药（消耗药品）', cost:{med:2},
        add_flags:['mercy_kept'],
        text:'隔着沉重铁门，你从通风口递出去两片珍贵安眠药，轻声说："奶奶，好好睡一觉吧，梦里天就亮了。"\n\n门外传来一句几乎听不清的"谢谢"。随后一切归于寂静。\n\n你损失了药品，却守住了末世里最难留下的人性底线。',
        euph:10, exposure:0 } },

    { id:'neighbor_revenge', day:[18,35], type:'threat', once:true, base_weight:140,
      conditions:{ required_flags:['neighbor_rejected'] },
      title:'王大爷的儿子', avatar:'👊',
      desc:'一个彪形大汉砸你的门："是你让我爸在楼道里冻死的！你给我出来！"\n\n监控显示他手里拿着一根钢管。身后还有两个人。',
      left:{ label:'开门道歉+给物资', cost:{food:8,water:5},
        text:'你给了他物资，告诉他当时的情况。他沉默了很久，接过物资，带着人走了。\n\n"我爸说你是好人。但你不是。"',
        exposureReduce:5 },
      right:{ label:'播放当天监控录像', euph:20, exposure:15,
        text:'录像显示王大爷是自己选择离开的。大汉看完，一言不发地走了。\n\n但你知道——他会记住这个地方。' } },

    // 七、债务后果事件（Phase 1 借贷套现→Phase 2 催收）
    { id:'debt_collector', day:[5,25], type:'threat', once:true, base_weight:180,
      conditions:{ required_flags:['heavy_debt'] },
      title:'网贷催收上门', avatar:'📱',
      desc:'对讲机突然响了。一个阴冷的声音："您在【极速网贷】的借款已逾期。我们已经定位到您的避难所。\n\n请在24小时内交出等值物资，否则我们将采取……非常规手段。"\n\n监控画面里，三个穿黑色冲锋衣的人正在楼道里用喷漆写你的名字。',
      left:{ label:'交物资消灾', cost:{food:12,water:8},
        add_flags:['debt_paid'],
        text:'你把一箱物资推出去。领头的拿走东西，在门上贴了张条："结清。"\n\n你看着缩水的物资储备，突然很怀念末日前"借呗额度到账"的那个提示音。',
        exposureReduce:10 },
      right:{ label:'钱？什么钱？末日了还催收？', euph:50, exposure:20,
        add_flags:['debt_refused'],
        text:'你在对讲机里回了一句："世界都要完了你还想着KPI？"\n\n对面沉默了五秒。"记住了。我们还会来的。"\n\n你关掉对讲机，倒了杯咖啡。末日里最解压的事——合法赖账。' } },

    { id:'organ_failure', day:[8,35], type:'threat', once:false, cooldown:10, base_weight:160,
      conditions:{ required_flags:['extreme_debt'] },
      title:'身体在还债', avatar:'💔',
      desc:'你从噩梦中惊醒。梦里有人在量你的肾。\n\n也许是心理压力，也许是别的什么——你的身体状态明显在恶化。头晕、乏力、偶尔视线模糊。\n\n这就是一键抵押"全部家当"的代价吧。有些东西，不只是房子车子。',
      left:{ label:'消耗医疗物资治疗', cost:{med:3},
        text:'你给自己打了一针营养针。症状暂时缓解。\n\n但你知道，这不是最后一次。欠下的迟早要还。',
        reward:{euph:5} },
      right:{ label:'硬扛', euph:10, exposure:0,
        text:'你忍着头晕吃了块巧克力。末日了，谁还在乎体检报告？\n\n（HP-8）',
        penalty:{hp:8} } },

    // 八、日常填充事件（低成本、可重复、短cooldown）
    // ============================================
    { id:'pipe_leak', day:[3,55], type:'random', once:false, cooldown:5,
      title:'水管破裂', avatar:'🔧',
      desc:'凌晨被滴水声吵醒——避难所内部一根水管冻裂了，净水正在流失。',
      left:{ label:'紧急修补', cost:{med:1},
        text:'你用急救箱里的胶带和绷带把水管缠好了。损失不大。', reward:{euph:5} },
      right:{ label:'拿桶接着用', euph:0, exposure:0,
        text:'你找了几个桶接水。虽然不太卫生，但总比浪费好。', penalty:{water:2} } },
    { id:'morale_check', day:[5,55], type:'random', once:false, cooldown:6,
      title:'深夜失眠', avatar:'🌙',
      desc:'又是一个睡不着的夜晚。你盯着天花板，脑海里全是末日前的画面——那些再也回不去的日常。',
      left:{ label:'翻出零食开个小派对', cost:{food:2},
        text:'你打开了一袋薯片和一罐可乐。垃圾食品从未如此美味。同伴们也醒了，围过来一起吃。', reward:{euph:20} },
      right:{ label:'写日记', euph:15, exposure:0,
        text:'你在一张纸上写了很多。写完之后，莫名其妙地觉得好了一点。' } },
    { id:'rat_invasion', day:[8,50], type:'random', once:false, cooldown:8,
      title:'鼠患', avatar:'🐀',
      desc:'储物间传来窸窸窣窣的声音。几只老鼠正在啃你的食物储备。',
      left:{ label:'消耗物资灭鼠', cost:{med:1},
        text:'你用消毒剂和陷阱解决了问题。储物间恢复安全。', reward:{euph:5} },
      right:{ label:'放着不管', euph:0, exposure:0,
        text:'老鼠越来越多。又有一批食物被啃坏了。', penalty:{food:3} } },
    { id:'sunset_photo', day:[15,55], type:'random', once:false, cooldown:9,
      title:'监控里的日落', avatar:'🌅',
      desc:'今天的监控画面捕捉到了罕见的一幕——乌云裂开了一条缝，夕阳的余晖洒在废墟上。末日以来第一次看到阳光。',
      left:{ label:'截图保存', cost:{},
        text:'你把这一帧画面存了下来。也许某天，可以给别人看看——末日里也有美的瞬间。', reward:{euph:15} },
      right:{ label:'关掉监控继续忙', euph:5, exposure:0,
        text:'你关掉了屏幕。感叹了一秒，然后继续清点物资。' } },
    { id:'supply_audit', day:[10,50], type:'random', once:false, cooldown:7,
      title:'物资盘点日', avatar:'📋',
      desc:'你决定做一次全面的物资盘点。翻箱倒柜的过程中，你在角落发现了之前遗漏的一些东西。',
      left:{ label:'仔细清点', cost:{},
        randomOutcomes:[
          { chance:0.4, text:'找到了几包被压在箱底的压缩饼干！', reward:{food:3} },
          { chance:0.3, text:'角落里有两瓶没开封的矿泉水。', reward:{water:2} },
          { chance:0.3, text:'只有灰尘和一只蟑螂。', reward:{euph:5} }
        ] },
      right:{ label:'大概齐就行', euph:3, exposure:0,
        text:'你扫了一眼，感觉差不多。有些东西还是不知道比较幸福。' } },
  ];
